//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DestinyAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class DB_Resource
    {
        public short Sl_No_ { get; set; }
        public string ResourceName { get; set; }
        public string ResourceLink { get; set; }
        public short ResourceID { get; set; }
        public string ResourceImage { get; set; }
        public short TeamID { get; set; }
    }
}
