//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DestinyAdmin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DB_Resource> DB_Resource { get; set; }
        public virtual DbSet<DB_Teams> DB_Teams { get; set; }
        public virtual DbSet<DB_Category> DB_Category { get; set; }
    
        //public virtual ObjectResult<GetResource_Result> GetResource(Nullable<int> id, Nullable<int> resourceid)
        //{
        //    var idParameter = id.HasValue ?
        //        new ObjectParameter("id", id) :
        //        new ObjectParameter("id", typeof(int));
    
        //    var resourceidParameter = resourceid.HasValue ?
        //        new ObjectParameter("resourceid", resourceid) :
        //        new ObjectParameter("resourceid", typeof(int));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetResource_Result>("GetResource", idParameter, resourceidParameter);
        //}
    
        //public virtual ObjectResult<GetTeams_Result> GetTeams()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTeams_Result>("GetTeams");
        //}
    }
}
